language: python
python:
  - "2.7"
  - "3.4"
install: "pip install -r requirements.txt"
script:
  - git clone https://github.com/erikbern/git-of-theseus
  - python analyze.py git-of-theseus --outdir got
  - python stack_plot.py got/cohorts.json
  - python survival_plot.py got/survival.json

  
